apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: quay.io/csatyam142/dockersamples/examplevotingapp_result
    ports:
     - containerPort: 80
